
parameters:
    arthem_fileupload.image_manager.class: Arthem\Bundle\FileUploadBundle\ImageManager
    arthem_fileupload.twig.extension.image.class: Arthem\Bundle\FileUploadBundle\Twig\Extension\ImageExtension

services:
    arthem_fileupload.image_manager:
        class: %arthem_fileupload.image_manager.class%
        arguments:
            - @liip_imagine.cache.manager
            - %arthem_fileupload.image.placeholders%
            - false

    arthem_fileupload.twig.extension.image:
        public: false
        class: %arthem_fileupload.twig.extension.image.class%
        arguments:
            - @arthem_fileupload.image_manager
        tags:
            - { name: twig.extension, alias: arthem_image }
