
services:
    arthem_file.image_manager:
        class: Arthem\Bundle\FileBundle\ImageManager
        arguments:
            - "@liip_imagine.cache.manager"
            - "%arthem_file.image.placeholders%"
            - false

    arthem_file.twig.extension.image:
        public: false
        class: Arthem\Bundle\FileBundle\Twig\Extension\ImageExtension
        arguments:
            - "@arthem_file.image_manager"
        tags:
            - { name: twig.extension, alias: arthem_image }
