
services:
    _defaults:
        autowire: true

    Arthem\Bundle\FileBundle\ImageManager:
        arguments:
            $placeholders: "%arthem_file.image.placeholders%"
            $cropActive: false

    Arthem\Bundle\FileBundle\Twig\Extension\ImageExtension:
        public: false
        tags:
            - { name: twig.extension, alias: arthem_image }
