
services:
    arthem_file.listener.uploadable:
        public: false
        class: Arthem\Bundle\FileBundle\EventListener\UploadableListener
        arguments:
            - "@stof_doctrine_extensions.uploadable.manager"
        tags:
            - { name: doctrine.event_subscriber }

    arthem_file.doctrine.listener.concrete_class:
        abstract: true
        class: Arthem\Bundle\FileBundle\Doctrine\AbstractMappingListener

    arthem_file.doctrine.listener.mapping:
        parent: arthem_file.doctrine.listener.concrete_class
        class: Arthem\Bundle\FileBundle\Doctrine\MappingListener
        arguments:
            - "%arthem_file.model.file.class%"
            - "%arthem_file.model.file.table%"
        tags:
            - { name: doctrine.event_subscriber }
