parameters:
    arthem_file.file_downloader.class: Arthem\Bundle\FileBundle\Downloader\FileDownloader
    arthem_file.file_upload_manager.class: Arthem\Bundle\FileBundle\Model\FileUploadManager
    arthem_file.http_client.class: Buzz\Client\Curl

services:
    arthem_file.http_client:
        public: false
        class: %arthem_file.http_client.class%

    arthem_file.file_downloader:
        class: %arthem_file.file_downloader.class%
        arguments:
            - @arthem_file.http_client
            - @stof_doctrine_extensions.uploadable.manager
            - %arthem_file.model.file.class%

    arthem_file.file_upload_manager:
        class: %arthem_file.file_upload_manager.class%
        scope: request
        arguments:
            - @arthem_base.object_manager
            - @form.factory
            - @arthem_file.image_manager
            - @templating.helper.assets
            - @translator
            - @request
