services:
    arthem_file.http_client:
        public: false
        class: GuzzleHttp\Client

    arthem_file.file_downloader:
        class: Arthem\Bundle\FileBundle\Downloader\FileDownloader
        arguments:
            - "@arthem_file.http_client"
            - "@stof_doctrine_extensions.uploadable.manager"
            - "%arthem_file.model.file.class%"

    arthem_file.file_upload_manager.factory:
        class: Arthem\Bundle\FileBundle\Model\FileUploadManagerFactory
        arguments:
            - "@doctrine"
            - "@form.factory"
            - "@arthem_file.image_manager"
            - "@assets.packages"
            - "@translator"
            - "@request_stack"

    arthem_file.file_upload_manager:
        class: Arthem\Bundle\FileBundle\Model\FileUploadManager
        factory: "arthem_file.file_upload_manager.factory:createManager"
        arguments:
            - "%arthem_file.model.file.class%"
