services:
    _defaults:
        autowire: true

    arthem_file.http_client:
        public: false
        class: GuzzleHttp\Client

    arthem_file.file_downloader:
        class: Arthem\Bundle\FileBundle\Downloader\FileDownloader
        arguments:
            $client: "@arthem_file.http_client"
            $fileClass: "%arthem_file.model.file.class%"

    Arthem\Bundle\FileBundle\Model\FileUploadManagerFactory: ~

    Arthem\Bundle\FileBundle\Model\FileUploadManager:
        factory: ['Arthem\Bundle\FileBundle\Model\FileUploadManagerFactory', createManagerFor]
        arguments:
            - "%arthem_file.model.file.class%"
